-- gamemode/cl_manifest_debug.lua
/// MANIFEST LINKS:
/// Principles: P-080 (Readability), C-009 (Commitment - Debugging)

-- This file is generated by tools/manifest_coverage.py
-- It contains ManifestData.Definitions and ManifestData.Mappings
include("cl_manifest_data.lua")

local C_BG = Color(20, 20, 20, 220)
local C_TEXT = Color(220, 220, 220, 255)
local C_ACCENT = Color(255, 180, 50, 255)
local C_SUBTLE = Color(150, 150, 150, 255)

local fontName = "ManifestDebugFont"
surface.CreateFont(fontName, {
    font = "Consolas",
    size = 14,
    weight = 500,
    antialias = true,
})

local function DrawManifestBox(ent, mapping)
    local ids = mapping
    if not ids or #ids == 0 then return end

    local x, y = ScrW() / 2 + 32, ScrH() / 2 + 32
    local w, h = 300, 24 + (#ids * 16) + 8
    
    -- Background
    draw.RoundedBox(4, x, y, w, h, C_BG)
    
    -- Header
    draw.SimpleText("MANIFEST ENFORCEMENT", fontName, x + 8, y + 4, C_ACCENT, TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP)
    draw.SimpleText(ent:GetClass(), fontName, x + w - 8, y + 4, C_SUBTLE, TEXT_ALIGN_RIGHT, TEXT_ALIGN_TOP)
    
    -- Content
    for i, id in ipairs(ids) do
        local def = ManifestData and ManifestData.Definitions and ManifestData.Definitions[id] or "Unknown"
        local lineY = y + 24 + (i-1) * 16
        
        -- Color code based on type
        local col = C_TEXT
        if id:StartWith("M-") then col = Color(255, 100, 100) -- Mechanic
        elseif id:StartWith("P-") then col = Color(100, 255, 100) -- Principle
        elseif id:StartWith("C-") then col = Color(100, 100, 255) -- Concept
        end
        
        draw.SimpleText(id, fontName, x + 8, lineY, col, TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP)
        draw.SimpleText(def, fontName, x + 50, lineY, C_TEXT, TEXT_ALIGN_LEFT, TEXT_ALIGN_TOP)
    end
end

hook.Add("HUDPaint", "EFT_ManifestDebug", function()
    -- Only if eft_dev is enabled (replicated ConVar)
    if GetConVarNumber("eft_dev") == 0 then return end
    
    -- Trace from eyes
    local ply = LocalPlayer()
    local tr = util.TraceLine({
        start = ply:EyePos(),
        endpos = ply:EyePos() + ply:GetAimVector() * 500,
        filter = ply
    })
    
    if tr.Entity and tr.Entity:IsValid() then
        local ent = tr.Entity
        local class = ent:GetClass()
        
        -- Look up mapping
        -- 1. Direct class match
        local mapping = ManifestData.Mappings[class]
        
        -- 2. "player" override
        if not mapping and ent:IsPlayer() then
            mapping = ManifestData.Mappings["player"]
        end
        
        -- 3. Base class fallback (rare in Lua, but possible)
        -- (Not implemented for simplicity/perf)
        
        if mapping then
            DrawManifestBox(ent, mapping)
        end
    end
end)
