/// MANIFEST LINKS:
/// Principles: P-010 (Sport Identity - Bot)
-- ============================================================================
-- BOT PATHFINDING
-- ============================================================================
-- Uses GMod's native NavMesh (generated by nav_generate / sv_nav.lua).
-- Falls back to direct line-of-sight movement when no nav mesh is loaded.
--
-- nav_generate is triggered automatically on first map load via sv_nav.lua.
-- The generated .nav file is saved to maps/<mapname>.nav and reused forever.
-- ============================================================================

BotPathfinder      = {}
BotPathfinder.Cache      = {} -- nextWaypoint Vector per bot
BotPathfinder.LastUpdate = {} -- CurTime() of last A* calculation per bot

local pathUpdateInterval = 0.5 -- Seconds between A* recalculations

-- ============================================================================
-- Path reconstruction helper (A*)
-- ============================================================================

local function ReconstructPath(cameFrom, current, startArea)
	local path = {}
	local curr = current
	while curr do
		table.insert(path, 1, curr)
		if curr == startArea then break end
		curr = cameFrom[curr:GetID()]
	end
	return path
end

-- ============================================================================
-- Public API
-- ============================================================================

--- Find the next waypoint toward targetPos using GMod NavMesh A*.
--- Returns nil when nav mesh is absent or a clear direct path exists.
---@param bot     Player  The bot entity
---@param targetPos Vector  Destination position
---@return Vector|nil
function BotPathfinder.GetNextWaypoint(bot, targetPos)
	if not navmesh.IsLoaded() then return nil end

	local botPos = bot:GetPos()

	-- Direct LOS check: hull trace matching player physics.
	-- If nothing is in the way, skip A* entirely and move straight.
	local tr = util.TraceHull({
		start  = botPos    + Vector(0, 0, 10),
		endpos = targetPos + Vector(0, 0, 10),
		mins   = Vector(-16, -16,  0),
		maxs   = Vector( 16,  16, 72),
		mask   = MASK_SOLID,
		filter = function(ent)
			-- Only care about map geometry, not other players/bots
			if ent:IsPlayer() or ent:IsNPC() then return false end
			return true
		end
	})
	if not tr.Hit then return nil end -- Clear path, direct move

	-- Throttle: return cached waypoint if we calculated recently
	if BotPathfinder.LastUpdate[bot] and
	   CurTime() - BotPathfinder.LastUpdate[bot] < pathUpdateInterval then
		return BotPathfinder.Cache[bot]
	end

	-- A* over GMod NavMesh areas
	local startArea = navmesh.GetNavArea(botPos,    200)
	local endArea   = navmesh.GetNavArea(targetPos, 200)

	if not IsValid(startArea) or not IsValid(endArea) then return nil end
	if startArea == endArea then return nil end -- Same area, go direct

	local openSet  = {startArea}
	local cameFrom = {}
	local gScore   = {[startArea:GetID()] = 0}
	local fScore   = {[startArea:GetID()] = startArea:GetCenter():Distance(targetPos)}

	local loops    = 0
	local maxLoops = 200 -- Safety cap

	while #openSet > 0 and loops < maxLoops do
		loops = loops + 1

		-- Pick area with lowest fScore
		local current, currentIndex
		local lowestF = math.huge
		for i, area in ipairs(openSet) do
			local f = fScore[area:GetID()] or math.huge
			if f < lowestF then
				lowestF      = f
				current      = area
				currentIndex = i
			end
		end

		if current == endArea then
			local path = ReconstructPath(cameFrom, current, startArea)
			if path[2] then
				local waypoint  = path[2]:GetCenter()
				-- Small jitter to prevent bot trains on shared paths
				waypoint.x = waypoint.x + math.random(-20, 20)
				waypoint.y = waypoint.y + math.random(-20, 20)

				-- Jump hint: if next area is significantly higher, tell the bot
				bot.PathJump = waypoint.z > botPos.z + 40

				BotPathfinder.Cache[bot]      = waypoint
				BotPathfinder.LastUpdate[bot] = CurTime()
				return waypoint
			end
			return nil
		end

		table.remove(openSet, currentIndex)

		for _, neighbor in ipairs(current:GetAdjacentAreas()) do
			local tentativeG = gScore[current:GetID()] +
			                   current:GetCenter():Distance(neighbor:GetCenter())
			local nID = neighbor:GetID()

			if tentativeG < (gScore[nID] or math.huge) then
				cameFrom[nID] = current
				gScore[nID]   = tentativeG
				fScore[nID]   = gScore[nID] + neighbor:GetCenter():Distance(targetPos)

				local inOpen = false
				for _, a in ipairs(openSet) do
					if a == neighbor then inOpen = true; break end
				end
				if not inOpen then
					table.insert(openSet, neighbor)
				end
			end
		end
	end

	return nil -- No path found within budget
end
